version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    depends_on:
      - backend
    networks:
      - naval-chess-network
    environment:
      - PORT=3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - naval-chess-network
    volumes:
      - backend-data:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    command: python app.py

networks:
  naval-chess-network:
    driver: bridge

volumes:
  backend-data: 